### ISSUE TITLE
Not gracefully handling malformed trapi query

### ISSUE THREAD

**Issue by GregHydeDartmouth** [di2ag/chp_api#19]
See [issue](https://github.com/NCATSTranslator/minihackathons/issues/15)

Solution: try except line 50 and on exception return empty message with appropriate error message.

**Comment by tursynay** [comment]
Hi Greg, any updates on this issue? We have the Translator mini-hackathon this week and I am trying to get updates on the issues we created two weeks ago. We will be rerunning the same queries and would be helpful to know where we stand with the issues recorded last week.

**Comment by GregHydeDartmouth** [comment]
Address on this [commit](https://github.com/di2ag/chp_api/commit/f6a5580eb6e82166210fc92d095c045bd3fec60b)
